'static'; var TEXTS = {
	'whoStarts': 'Kdo začne?',
	'throwDice': 'Hoď kostkami',
	'tossCoin': 'Hoď mincí',
	'apply': 'Použít',
	'back': 'Zpět',
	'coin1': 'Hlava',
	'coin2': 'Orel',
	'settings': 'Nastavení',
	'timer': 'Nezdržuj',
	'initScore': 'Počáteční skóre',
	'plCount': 'Počet hráčů',
	'plColors': 'Barvy hráčů',
	'countdown': 'Odpočet',
	'play': '▷', // https://stackoverflow.com/a/27053825/6603609
	'pause': '❘ ❘',
	'stop': '◻',
	'restart': '⟲',
	'end': 'KONEC',
};