'static'; TEXTS = {
	'whoStarts': 'Kdo začne?',
	'throwDice': 'Hoď kostkami',
	'tossCoin': 'Hoď mincí',
	'apply': 'Použít',
	'back': 'Zpět',
	'coin1': 'Hlava',
	'coin2': 'Orel',
	'settings': 'Nastavení',
	'timer': 'Nezdržuj',
	'initScore': 'Počáteční skóre',
	'plCount': 'Počet hráčů',
	'plColors': 'Barvy hráčů',
	'countdown': 'Odpočet',
	'set': 'Nastav',
	'run': 'Spusť',
	'pause': 'Pauza',
	'stop': 'Stop',
	'restart': 'Restart',
	'end': 'KONEC!!',
};