'static'; TEXTS = {
	'whoStarts': 'Who\'ll start?',
	'throwDice': 'Throw dice',
	'tossCoin': 'Toss coin',
	'apply': 'Apply',
	'back': 'Back',
	'coin1': 'Head',
	'coin2': 'Tail',
	'settings': 'Settings',
	'timer': 'Don\'t stall',
	'initScore': 'Initial score',
	'plCount': 'Player count',
	'plColors': 'Player colors',
	'countdown': 'Countdown',
	'play': '▷',
	'pause': '❘ ❘',
	'stop': '◻',
	'restart': '⟲',
	'end': 'END!!',
};