name: C/C++ CI

on:
  push:
    branches: 
      - devel
      - master

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: configure-windows
      if: ${{ matrix.os }} == 'windows-latest'
      run: cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" .
    - name: configure-ubuntu
      if: ${{ matrix.os }} == 'ubuntu-latest'
      run: cmake .
    - name: make
      run: make
    - name: tests
      run: ctest
    - name: package
      run: cpack
