name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  build:
    runs-on: [ windows-2022, ubuntu-latest ]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@1.13
      with:
        cmake-version: '3.23.2'
    
    - name: Configure
      shell: cmd
      run: |
        cmake --version
        mkdir "${{env.BUILD_DIR}}"
        cd "${{env.BUILD_DIR}}"
        cmake ..
    
    - name: Build
      shell: cmd
      working-directory: ${{env.BUILD_DIR}}
      run: |
        cmake --build . --config Release
    
    - name: Test
      shell: cmd
      working-directory: ${{env.BUILD_DIR}}
      run: |
        ctest -C Release
    
    - name: Pack
      working-directory: ${{env.BUILD_DIR}}
      run: cpack
    
    - name: Store artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: ${{env.BUILD_DIR}}/*.zip
        retention-days: 1
